config/routes.rb
# == Route Map
#
#                          Prefix Verb   URI Pattern                                                   Controller#Action
#                            root GET    /                                                             static_pages#home
#                    contact_page GET    /contact(.:format)                                            static_pages#contact
#                         contact POST   /contact(.:format)                                            static_pages#send_contact
#                      about_page GET    /about(.:format)                                              static_pages#about
#                new_user_session GET    /login(.:format)                                              users/sessions#new
#                    user_session POST   /login(.:format)                                              users/sessions#create
#            destroy_user_session DELETE /logout(.:format)                                             users/sessions#destroy
#                   user_password POST   /accounts/password(.:format)                                  devise/passwords#create
#               new_user_password GET    /accounts/password/new(.:format)                              devise/passwords#new
#              edit_user_password GET    /accounts/password/edit(.:format)                             devise/passwords#edit
#                                 PATCH  /accounts/password(.:format)                                  devise/passwords#update
#                                 PUT    /accounts/password(.:format)                                  devise/passwords#update
#        cancel_user_registration GET    /accounts/register/cancel(.:format)                           devise/registrations#cancel
#               user_registration POST   /accounts/register(.:format)                                  devise/registrations#create
#           new_user_registration GET    /accounts/register/sign_up(.:format)                          devise/registrations#new
#          edit_user_registration GET    /accounts/register/edit(.:format)                             devise/registrations#edit
#                                 PATCH  /accounts/register(.:format)                                  devise/registrations#update
#                                 PUT    /accounts/register(.:format)                                  devise/registrations#update
#                                 DELETE /accounts/register(.:format)                                  devise/registrations#destroy
#                     user_unlock POST   /accounts/unlock(.:format)                                    devise/unlocks#create
#                 new_user_unlock GET    /accounts/unlock/new(.:format)                                devise/unlocks#new
#                                 GET    /accounts/unlock(.:format)                                    devise/unlocks#show
#                 collection_item GET    /collections/:collection_id/:id(.:format)                     collection_items#show
#                     collections GET    /collections(.:format)                                        collections#index
#                      collection GET    /collections/:id(.:format)                                    collections#show
#                       enquiries POST   /enquiries(.:format)                                          enquiries#create
#         change_password_account POST   /account/change-password(.:format)                            accounts#change_password
#       account_enquiry_responses GET    /account/enquiries/:enquiry_id/responses(.:format)            responses#index
#                                 POST   /account/enquiries/:enquiry_id/responses(.:format)            responses#create
#               account_enquiries GET    /account/enquiries(.:format)                                  enquiries#index
#                 account_enquiry DELETE /account/enquiries/:id(.:format)                              enquiries#destroy
#     account_authorization_order POST   /account/authorizations/:authorization_id/order(.:format)     orders#create
# new_account_authorization_order GET    /account/authorizations/:authorization_id/order/new(.:format) orders#new
#          account_authorizations GET    /account/authorizations(.:format)                             authorizations#index
#           account_authorization DELETE /account/authorizations/:id(.:format)                         authorizations#destroy
#     account_order_retry_payment GET    /account/orders/:order_id/payment/retry(.:format)             payment#retry
# account_order_authorize_payment POST   /account/orders/:order_id/payment/authorize(.:format)         payment#authorize
#    account_order_payment_errors GET    /account/orders/:order_id/payment/errors(.:format)            payment#errors
#                  account_orders GET    /account/orders(.:format)                                     orders#index
#                   account_order GET    /account/orders/:id(.:format)                                 orders#show
#                         account GET    /account(.:format)                                            accounts#show
#                      refile_app        /attachments                                                  #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  # Home Page
  root 'static_pages#home'

  # Contact Page
  get 'contact', to: 'static_pages#contact', as: :contact_page
  post 'contact', to: 'static_pages#send_contact', as: :contact

  # About Page
  get 'about', to: 'static_pages#about', as: :about_page

  # Authentication (Devise) Routes
  devise_for :users,
             path: '',
             path_names: {
                 'sign_in': 'login',
                 'sign_out': 'logout',
                 'password': 'accounts/password',
                 'unlock': 'accounts/unlock',
                 'registration': 'accounts/register',
                 'sign_up': 'sign_up'
             },
             controllers: {
                 sessions: 'users/sessions'
             }

  # Show Collection Item
  get 'collections/:collection_id/:id', to: 'collection_items#show', as: :collection_item

  # Show Collection
  resources :collections, only: [:show, :index]

  # Create Enquiry
  resources :enquiries, only: [:create]

  # Account Enquiries
  # Account Changes
  # Purchase Authorizations
  # Purchase Orders
  resource :account, only: [:show] do
    member do
      post 'change-password', to: 'accounts#change_password', as: :change_password
    end
    resources :enquiries, only: [:index, :destroy] do
      resources :responses, only: [:create, :index]
    end
    resources :authorizations, only: [:index, :destroy] do
      resource :order, only: [:new, :create]
    end
    resources :orders, only: [:index, :show] do
      get 'payment/retry', to: 'payment#retry', as: :retry_payment
      post 'payment/authorize', to: 'payment#authorize', as: :authorize_payment
      get 'payment/errors', to: 'payment#errors', as: :payment_errors
    end
  end
  get 'accounts/sale_authorizations', to: 'authorizations#index', as: :account_redirect
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'content', except: [:home]

  def home
    render layout: 'home'
  end

  def contact
    @contact = ContactSubmission.new
  end

  def send_contact
    ContactSubmission.new(message_params).send
    redirect_to contact_path, notice: 'Message sent. You will receive a response as quickly as possible'
  end

  def about
    render layout: 'darkmenu_content'
  end

  private

    def message_params
      params.require(:contact_submission).permit(:message, :email, :subject, :name)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_top_menu.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid page-container">
    <button class="navbar-toggler hidden-sm-up float-xs-left" type="button" data-toggle="collapse" data-target="#collapsableMenu">
      &#9776;
    </button>
    <div class="float-right hidden-sm-up" id="logo">
      <%= image_tag 'RR-logo.png', height: 155, width: 137, class: 'img-fluid' %>
    </div>
    <div class='clearfix hidden-sm-up'></div>
    <div class="float-xs-right collapse navbar-toggleable-xs" id="collapsableMenu">
      <ul class="nav navbar-nav text-right" id="main-menu">
        <% if page?('about') %>
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Collections', collections_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_page_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Account', account_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="nav navbar-nav float-xs-right" id="social-media-menu">
        <li class="nav-item">
          <%= link_to(image_tag('facebook-icon-white.png', width: 9, height: 18), 'https://www.facebook.com/RhionRomany', class: 'nav-link', target: '_blank') %>
        </li>
        <li class="nav-item">
          <%= link_to(image_tag('twitter-icon-white.png', width: 20, height: 18), 'https://twitter.com/RhionRomany', class: 'nav-link', target: '_blank') %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<%
   pagetitle = 'About'
   description = 'About Rhion Romany Designs'
   meta title: pagetitle,
        description: description,
        keywords: %w(about rhion romany fashion monday wear carnival 2016),
        og: {
            title: pagetitle,
            url: about_page_url,
            description: description
        }
%>

<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid page-container">
    <h1 class="text-xs-center" id="pagetitle">
      About
    </h1>
    <section>
      <p class="lead text-xs-center"><strong>Fashion resides freely within Rhion Romany</strong></p>
      <hr class="m-y-md">
      <p>For quite some time, this alumnus of Queen’s Royal College has been an ardent admirer of and inspired by well-known local & international fashion impresarios,
        who have fine-tuned their skills to transform and enhance the global meaning of style to suit ever-changing social trends.
        A Caribbean climate of inspiration allowed Romany to channel his natural ability of selecting edgy, contemporary designs for his clients via his wildly successful retail boutique, KrAze.</p>
      <p>The stirring of his honed design talent, however, came with the successful launch of his exclusive swimwear collection for summer for Cropover 2012.</p>
      <p>A mere 2 years later, the young designer has amassed a sizeable Fan base, as well as glowing praises from his peers in the industry.
        The experience also served as a constant state of creative awakening: it challenged the daring 24 year-old to nurture & explore the untamed arena of fashion design.
      </p>
      <p>For Rhion, design inspiration is easily motivated by the evolution of the Trinidadian social lifestyle. His productions draw real-time references from the spaces that he occupies,
        and he takes pride in the progress of his generation that continue to reciprocate creative avenues that keep fashion trends unique, relatable and current.</p>
    </section>
    <section>
      <p class="lead text-xs-center"><strong>The end point: a celebration of the power of the female form</strong></p>
      <hr class="m-y-md">
      <p>Rhion’s point of view & impeccable taste levels remain highly consistent for his premiere collection. He is a man who unapologetically continues to design for a woman, appreciate body construction and encourage his female clients to reclaim & celebrate their feminine form.
        There is a distinct air of elegance and richness embodied in Rhion’s design taste, and one can always expect progressive pieces of work on his runway that wholly rejects tameness and sameness in approach.</p>
      <p>With such highly-applauded collections as “Monroe” and “She Wolf” under his belt, the birth and growth of the Rhion Romany Brand has unleashed an energy of confidence for this promising designer to give the masses a taste of “the refined”.</p>
      <p>To date, his designs have been worn by everyone from America’s Next Top Model’s Bianca Golden to the stage dancers for award-winning Soca Sensation Machel Montano.
        His creations have graced the runway for audiences such as CreativeTT’s “Masquerade” event in honour of Vogue Italia & HOT Couture in St. Lucia Jazz & Arts Festival. The ЯR brand has now announced a partnership with TRIBE Carnival for an exclusive line of Monday Wear for the 2015 season.</p>
      <p>With his next collection “Domina” on the way, his point of view comfortably positions his female clientele in a innovative space for Trinidad & Tobago: armed with the audacity to always be bold, sophisticated and timeless, ready to take on the world.</p>
    </section>
  </div>
</div>

app/views/static_pages/contact.html.erb
<%
   pagetitle = 'Contact'
   description = 'Contact Rhion Romany Designs'
   meta title: pagetitle,
        description: description,
        keywords: %w(rhion romany fashion monday wear carnival 2016),
        og: {
            title: pagetitle,
            url: contact_page_url,
            description: description
        }

   if user_signed_in?
     @contact.name = current_user.name
     @contact.email = current_user.email
   end
%>

<%= render 'shared/flash_messages' %>

<h1 class="text-xs-center" id="pagetitle">Contact</h1>

<div class="page-container container-fluid" id='contact-container'>
  <div class="row">
    <!-- Contact Us Form -->
    <div class="col-xs-12 col-sm-6" id="contact-form">
      <h2 id="subtitle">Message Us!</h2>
      <%= form_for @contact, url: contact_path, method: :post do |f| %>
        <fieldset class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </fieldset>

         <fieldset class="form-group">
           <%= f.label :email %>
           <%= f.email_field :email, class: 'form-control', required: true %>
         </fieldset>

         <fieldset class="form-group">
           <%= f.label :subject %>
           <%= f.text_field :subject, class: 'form-control', required: true %>
         </fieldset>

         <fieldset class="form-group">
           <%= f.label :message %>
           <%= f.text_area :message, class: 'form-control', required: true %>
         </fieldset>

         <%= f.submit 'Send', class: 'btn btn-secondary' %>
      <% end %>
    </div>

    <!-- Contact Us Info -->
    <div class="col-xs-12 col-sm-6 text-xs-right" id="contact-info">
      <h2 id="subtitle">Contact Information</h2>
      <p id="phone"><i class="fa fa-phone-square"></i>(868) 787-1166</p>
      <p id="email"><i class="fa fa-envelope"></i>info@rhionromany.com</p>
      <p id="facebook"><a href="https://www.facebook.com/RhionRomany"><i class="fa fa-facebook-official"></i>facebook.com/RhionRomany</a></p>
      <p id="twitter"><a href="https://twitter.com/RhionRomany"><i class="fa fa-twitter-square"></i>twitter.com/RhionRomany</a></p>
      <p id="instagram"><a href="https://instagram.com/rhionromany"><i class="fa fa-instagram"></i>instagram.com/rhionromany</a></p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%
   pagetitle = 'Welcome to Rhion Romany'
   description = 'Welcome to Rhion Romany Designs'
   meta title: pagetitle,
        description: description,
        keywords: %w(rhion romany fashion monday wear carnival 2016),
        og: {
            title: pagetitle,
            url: root_url,
            description: description
        }
%>

<div class="scene parallax" id="first">
  <div class="scene-background"></div>
  <p class="text-xs-center" id="first-text">
    <span class="green">Rhion Romany</span><br/>
    is the embodiment<br/>
    of boldness,<br/>
    sophistication<br/>
    and<br/>
    timeliness.
  </p>
</div>

<div class="scene parallax" id="second">
  <div class="scene-background"></div>
  <p class="text-xs-center" id="second-text"><span id="murder-she-wrote-title">Murder She Wrote</span><br/>
    <%= link_to 'See Full Collection', collection_path('murder-she-wrote'), class: 'text-xs-center collection-link' %>
  </p>
</div>

<div class="scene parallax" id="third">
  <div class="scene-background"></div>
  <p class="text-xs-center" id="third-text">
    <span class="green">Rhion Romany</span><br/>
    celebrates<br/>
    the feminine form<br/>
    with highly consistent<br/>
    impeccable<br/>
    taste levels.
  </p>
</div>

<div class="scene parallax" id="fourth">
  <div class="scene-background"></div>
  <p class="text-xs-center" id="fourth-text"><span id="monday-wear-title"><span class="lighter">&#1071;</span>R Monday Wear 2016</span><br/>
    <%= link_to 'See Full Collection', collection_path('monday-wear-2016'), class: 'text-xs-center collection-link' %>
  </p>
</div>