config/routes.rb
# == Route Map
#
#                          Prefix Verb   URI Pattern                                                   Controller#Action
#                            root GET    /                                                             static_pages#home
#                    contact_page GET    /contact(.:format)                                            static_pages#contact
#                         contact POST   /contact(.:format)                                            static_pages#send_contact
#                      about_page GET    /about(.:format)                                              static_pages#about
#                new_user_session GET    /login(.:format)                                              users/sessions#new
#                    user_session POST   /login(.:format)                                              users/sessions#create
#            destroy_user_session DELETE /logout(.:format)                                             users/sessions#destroy
#                   user_password POST   /accounts/password(.:format)                                  devise/passwords#create
#               new_user_password GET    /accounts/password/new(.:format)                              devise/passwords#new
#              edit_user_password GET    /accounts/password/edit(.:format)                             devise/passwords#edit
#                                 PATCH  /accounts/password(.:format)                                  devise/passwords#update
#                                 PUT    /accounts/password(.:format)                                  devise/passwords#update
#        cancel_user_registration GET    /accounts/register/cancel(.:format)                           devise/registrations#cancel
#               user_registration POST   /accounts/register(.:format)                                  devise/registrations#create
#           new_user_registration GET    /accounts/register/sign_up(.:format)                          devise/registrations#new
#          edit_user_registration GET    /accounts/register/edit(.:format)                             devise/registrations#edit
#                                 PATCH  /accounts/register(.:format)                                  devise/registrations#update
#                                 PUT    /accounts/register(.:format)                                  devise/registrations#update
#                                 DELETE /accounts/register(.:format)                                  devise/registrations#destroy
#                     user_unlock POST   /accounts/unlock(.:format)                                    devise/unlocks#create
#                 new_user_unlock GET    /accounts/unlock/new(.:format)                                devise/unlocks#new
#                                 GET    /accounts/unlock(.:format)                                    devise/unlocks#show
#                 collection_item GET    /collections/:collection_id/:id(.:format)                     collection_items#show
#                     collections GET    /collections(.:format)                                        collections#index
#                      collection GET    /collections/:id(.:format)                                    collections#show
#                       enquiries POST   /enquiries(.:format)                                          enquiries#create
#         change_password_account POST   /account/change-password(.:format)                            accounts#change_password
#       account_enquiry_responses GET    /account/enquiries/:enquiry_id/responses(.:format)            responses#index
#                                 POST   /account/enquiries/:enquiry_id/responses(.:format)            responses#create
#               account_enquiries GET    /account/enquiries(.:format)                                  enquiries#index
#                 account_enquiry DELETE /account/enquiries/:id(.:format)                              enquiries#destroy
#     account_authorization_order POST   /account/authorizations/:authorization_id/order(.:format)     orders#create
# new_account_authorization_order GET    /account/authorizations/:authorization_id/order/new(.:format) orders#new
#          account_authorizations GET    /account/authorizations(.:format)                             authorizations#index
#           account_authorization DELETE /account/authorizations/:id(.:format)                         authorizations#destroy
#     account_order_retry_payment GET    /account/orders/:order_id/payment/retry(.:format)             payment#retry
# account_order_authorize_payment POST   /account/orders/:order_id/payment/authorize(.:format)         payment#authorize
#    account_order_payment_errors GET    /account/orders/:order_id/payment/errors(.:format)            payment#errors
#                  account_orders GET    /account/orders(.:format)                                     orders#index
#                   account_order GET    /account/orders/:id(.:format)                                 orders#show
#                         account GET    /account(.:format)                                            accounts#show
#                      refile_app        /attachments                                                  #<Refile::App app_file="/Users/royaltyclubvp/.rvm/gems/ruby-2.2.3/gems/refile-0.6.2/lib/refile/app.rb">
#

Rails.application.routes.draw do

  # Home Page
  root 'static_pages#home'

  # Contact Page
  get 'contact', to: 'static_pages#contact', as: :contact_page
  post 'contact', to: 'static_pages#send_contact', as: :contact

  # About Page
  get 'about', to: 'static_pages#about', as: :about_page

  # Authentication (Devise) Routes
  devise_for :users,
             path: '',
             path_names: {
                 'sign_in': 'login',
                 'sign_out': 'logout',
                 'password': 'accounts/password',
                 'unlock': 'accounts/unlock',
                 'registration': 'accounts/register',
                 'sign_up': 'sign_up'
             },
             controllers: {
                 sessions: 'users/sessions'
             }

  # Show Collection Item
  get 'collections/:collection_id/:id', to: 'collection_items#show', as: :collection_item

  # Show Collection
  resources :collections, only: [:show, :index]

  # Create Enquiry
  resources :enquiries, only: [:create]

  # Account Enquiries
  # Account Changes
  # Purchase Authorizations
  # Purchase Orders
  resource :account, only: [:show] do
    member do
      post 'change-password', to: 'accounts#change_password', as: :change_password
    end
    resources :enquiries, only: [:index, :destroy] do
      resources :responses, only: [:create, :index]
    end
    resources :authorizations, only: [:index, :destroy] do
      resource :order, only: [:new, :create]
    end
    resources :orders, only: [:index, :show] do
      get 'payment/retry', to: 'payment#retry', as: :retry_payment
      post 'payment/authorize', to: 'payment#authorize', as: :authorize_payment
      get 'payment/errors', to: 'payment#errors', as: :payment_errors
    end
  end
  get 'accounts/sale_authorizations', to: 'authorizations#index', as: :account_redirect
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                    :integer          not null, primary key
#  sale_authorization_id :integer
#  collection_item_id    :integer
#  address_id            :integer
#  user_id               :integer
#  quantity              :integer
#  bra_size              :string
#  bust_size             :string
#  waist_size            :string
#  hip_size              :string
#  additional_info       :text
#  transaction_id        :string
#  payment_cents         :integer
#  status                :integer          default(0)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  order_number          :string
#  credit_card           :string
#
# Indexes
#
#  index_orders_on_address_id             (address_id)
#  index_orders_on_collection_item_id     (collection_item_id)
#  index_orders_on_sale_authorization_id  (sale_authorization_id)
#  index_orders_on_user_id                (user_id)
#

class Order < ActiveRecord::Base
  # Set status as enum
  enum status: %i(submitted paid fulfilled cancelled)

  # Apply Money Adapter
  monetize :payment_cents

  # Virtual Readers
  #
  # Billing Address Accessors
  attr_accessor :billing_street_address_1, :billing_street_address_2,
                :billing_city, :billing_state, :billing_zip_code, :billing_country,
                :cardholder_name, :email_address, :phone_number
  # Currency Accessor
  attr_accessor :currency

  # Token Accessor
  attr_accessor :token

  # Relationships
  #
  # Created from a SALE AUTHORIZATION
  belongs_to :sale_authorization, inverse_of: :order

  # Includes a COLLECTION ITEM
  belongs_to :collection_item, inverse_of: :orders

  # Submitted by a USER
  belongs_to :user, inverse_of: :orders

  # Has one ADDRESS
  belongs_to :address, inverse_of: :orders

  # Has TRANSACTION_ERRORS
  has_many :transaction_errors, inverse_of: :order

  # Data Handlers
  #
  # Address Attribute Handlers
  accepts_nested_attributes_for :address,
                                reject_if: :all_blank


  # Model Callbacks
  before_save :set_collection_item_if_missing, :set_user_id_if_missing
  after_create :purchase


  # Callback Methods
  #
  # Set Collection Item ID
  def set_collection_item_if_missing
    self.collection_item ||= self.sale_authorization.collection_item
  end

  # Set User ID
  def set_user_id_if_missing
    self.user ||= self.sale_authorization.user
  end

  # Instance Methods
  #
  # Create Unique Identifier for Merchant Order ID
  def merchant_id
    "I#{self.collection_item_id}UID#{self.user_id}"
  end

  # Checkout Parameters
  def checkout_params
    params = {
        merchantOrderId: merchant_id,
        token: self.token,
        currency: self.currency,
        lineItems: line_items,
        billingAddr: billing_attributes
    }
  end

  # Create Purchase
  def purchase
    begin
      result = Twocheckout::Checkout.authorize(checkout_params)
      self.transaction_id = result["transactionId"].to_s
      self.order_number = result["orderNumber"].to_s
      self.paid!
      self.sale_authorization.completed!
      true
    rescue Twocheckout::TwocheckoutError => e
      self.transaction_errors.create(message: e.message)
      false
    end
  end


  # Convenience Methods
  #
  # Return Hash of Billing Address Attributes
  def billing_attributes
    attributes = {
        name: self.cardholder_name,
        addrLine1: self.billing_street_address_1,
        addrLine2: self.billing_street_address_2,
        city: self.billing_city,
        state: self.billing_state,
        zipCode: self.billing_zip_code,
        country: self.billing_country,
        email: self.email_address,
        phoneNumber: self.phone_number
    }
  end

  def shipping_attributes
    attributes = {
        name: self.user.name,
        addrLine1: self.address.street_address_1,
        addrLine2: self.address.street_address_2,
        city: self.address.city,
        state: self.address.state,
        zipCode: self.address.zip_code,
        country: self.address.country
    }
  end

  # Return Hash of Line Items
  def line_items
    attributes = [
        {
            type: 'product',
            name: "#{self.collection_item.name} - #{self.collection_item.collection.name} Collection",
            quantity: self.quantity,
            price: self.payment_cents/100.to_f,
            tangible: 'Y',
            productId: self.collection_item_id,
            options: [
                {
                    optName: 'Bra Size',
                    optValue: self.bra_size
                },
                {
                    optName: 'Bust Size',
                    optValue: self.bust_size
                },
                {
                    optName: 'Waist Size',
                    optValue: self.waist_size
                },
                {
                    optName: 'Hip Size',
                    optValue: self.hip_size
                },
                {
                    optName: 'Additional Info',
                    optValue: self.additional_info
                }
            ]
        }
    ]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  layout 'content'
  include OrdersHelper

  def new
    @sale_authorization = SaleAuthorization.includes(collection_item: :collection).find(params[:authorization_id])
  end

  def create
    Order.create(order_params)
    redirect_to account_order_path(current_user.orders.last)
  end

  def index
    @user = User.includes(orders: :collection_item).find(current_user.id)
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:cardholder_name, :credit_card, :currency, :email_address, :additional_info, :billing_city, :billing_state,
    :billing_street_address_1, :billing_street_address_2, :billing_zip_code, :billing_country, :waist_size, :phone_number, :bra_size, :bust_size, :hip_size, :quantity,
    :payment, :token, :collection_item_id, :sale_authorization_id, :user_id, address_attributes: [:street_address_1, :street_address_2, :city, :state, :zip_code, :country])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  # Set Up Order Object to include New Address Attributes
  def setup_order(order)
    order.build_address ||= Address.new
    order
  end

  # Return Formatted Date According to Status of Order
  def order_status_date(order, element, html_class)
    date, id, label = ''
    case order.status
      when 'submitted'
        date = order.created_at
        id = 'date-submitted'
        label = 'Date Submitted: '
      when 'paid'
        date = order.updated_at
        id = 'date-paid'
        label = 'Date Paid: '
      when 'fulfilled'
        date = order.updated_at
        id = 'date-fulfilled'
        label = 'Date Fulfilled: '
      when 'cancelled'
        date = order.updated_at
        id = 'date-cancelled'
        label = 'Date Cancelled: '
      else
    end
    content_tag(element, "<strong>#{label}</strong>#{date.strftime('%m/%d/%Y')}".html_safe, {class: html_class, id: id})
  end
end

app/views/orders/_order.html.erb
<div class="card">
  <%= attachment_image_tag(order.collection_item, :image, :fit, 650, 600, {alt: order.collection_item.name, class: 'img-fluid card-img-top'}) %>
  <div class="card-block">
    <h4 class="card-title"><%= order.collection_item.name %><small class='text-muted'> <%= order.collection_item.collection.name %></small></h4>
    <p><strong>Status: </strong><%= order.status.capitalize %></p>
    <div class="btn-group enquiry-options" role="group" aria-label="Authorization Options">
      <% if order.submitted? %>
        <%= link_to 'Payment Errors', account_order_payment_errors_path(order), class: 'btn btn-danger btn-sm' %>
      <% end %>
      <%= link_to 'View Order Details', account_order_path(order), class: 'btn btn-secondary btn-sm' %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<%
   pagetitle = 'My Account - Orders'
   description = 'Rhion Romany Customer Account Orders Page'
   meta title: pagetitle,
        description: description
%>

<h1 class="text-xs-center" id="pagetitle">My Account</h1>

<%= render 'accounts/account_menu' %>

<% if @user.orders.count > 0 %>
    <div class="card-columns page-container container-fluid" id="orders">
      <%= render @user.orders %>
    </div>
<% else %>
    <div class="page-container empty-list container-fluid" id="empty-orders">
      <p class="text-xs-center lead">No orders were found for your account</p>
    </div>
<% end %>

app/views/orders/new.html.erb
<%
   pagetitle = 'My Account - Place New Order'
   description = 'Rhion Romany Customer Account New Order Page'
   meta title: pagetitle,
        description: description
%>

<h1 class="text-xs-center" id="pagetitle">Place New Order</h1>

<div class="page-container container-fluid">
  <!-- Errors -->
  <div id="checkout-errors">

  </div>

  <!-- Order Form -->
  <%= form_for setup_order(@sale_authorization.build_order), url: account_authorization_order_path(@sale_authorization), html: {class: 'order-form'}, method: :post do |f| %>
    <%= f.hidden_field :collection_item_id, value: @sale_authorization.collection_item_id %>
    <%= f.hidden_field :user_id, value: @sale_authorization.user_id %>
    <%= f.hidden_field :sale_authorization_id %>
    <%= f.hidden_field :payment, value: @sale_authorization.price %>
    <%= f.hidden_field :currency, value: 'USD' %>
    <%= f.hidden_field :quantity, value: 1 %>
    <%= f.hidden_field :token %>
    <%= f.hidden_field :credit_card %>
    <div id="order-container" class="row">
      <div class="col-xs-12 col-sm-2" id="collection-item-image">
        <%= attachment_image_tag(@sale_authorization.collection_item, :image, :fit, 600, 650, {alt: @sale_authorization.collection_item.name, class: 'img-fluid'}) %>
      </div>
      <div class="col-xs-12 col-sm-5" id="address-container">
        <div class="card">
          <div class="card-header">
            Shipping Address
          </div>
          <div class="card-block">
            <%= f.fields_for :address do |address_field| %>
              <fieldset class="form-group">
                <%= address_field.label :street_address_1, 'Street Address Line 1*' %>
                <%= address_field.text_field :street_address_1, class: 'form-control address_1' %>
              </fieldset>

              <fieldset class="form-group">
                <%= address_field.label :street_address_2, 'Street Address Line 2' %>
                <%= address_field.text_field :street_address_2, class: 'form-control address_2' %>
              </fieldset>

              <div class="row">
                <div class="col-xs-5">
                  <fieldset class="form-group">
                    <%= address_field.label :city, "City*" %>
                    <%= address_field.text_field :city, class: 'form-control city' %>
                  </fieldset>
                </div>

                <div class="col-xs-3">
                  <fieldset class="form-group state-container">
                    <%= address_field.label :state %>
                    <%= address_field.text_field :state, class: 'form-control state' %>
                  </fieldset>
                </div>

                <div class="col-xs-4">
                  <fieldset class="form-group zipcode-container">
                    <%= address_field.label :zip_code %>
                    <%= address_field.text_field :zip_code, class: 'form-control zip_code' %>
                  </fieldset>
                </div>
              </div>

              <fieldset class="form-group">
                <%= address_field.label :country %>
                <%= address_field.country_select :country, {priority_countries: ["US"], format: :with_alpha3}, class: 'c-select country' %>
              </fieldset>
            <% end %>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <div class="float-xs-left">Billing Address</div>
            <div class="float-xs-right"><button id="same-as-shipping" role="button" class="btn btn-sm">Same as Above</button></div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">
            <fieldset class="form-group">
              <%= f.label :billing_street_address_1, 'Street Address Line 1*' %>
              <%= f.text_field :billing_street_address_1, class: 'form-control address_1' %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :billing_street_address_2, 'Street Address Line 2' %>
              <%= f.text_field :billing_street_address_2, class: 'form-control address_2' %>
            </fieldset>

            <div class="row">
              <div class="col-xs-5">
                <fieldset class="form-group">
                  <%= f.label :billing_city, "City*" %>
                  <%= f.text_field :billing_city, class: 'form-control city' %>
                </fieldset>
              </div>

              <div class="col-xs-3">
                <fieldset class="form-group state-container">
                  <%= f.label :billing_state, 'State' %>
                  <%= f.text_field :billing_state, class: 'form-control state' %>
                </fieldset>
              </div>

              <div class="col-xs-4">
                <fieldset class="form-group zipcode-container">
                  <%= f.label :billing_zip_code, 'Zip Code' %>
                  <%= f.text_field :billing_zip_code, class: 'form-control zip_code' %>
                </fieldset>
              </div>
            </div>

            <fieldset class="form-group">
              <%= f.label :billing_country, 'Country' %>
              <%= f.country_select :billing_country, {priority_countries: ["US"], format: :with_alpha3}, class: 'c-select country' %>
            </fieldset>

          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-5" id="credit-card-container">
        <div class="card">
          <div class="card-header">
            Order Information
          </div>
          <% unless @sale_authorization.message.nil? %>
              <div class="card-block">
                <p><%= @sale_authorization.message %></p>
              </div>
          <% end %>
          <div class="card-block">
            <div class="row">
              <div class="col-xs-4">
                <fieldset class="form-group">
                  <%= f.label :bra_size %>
                  <%= f.text_field :bra_size, class: 'form-control' %>
                </fieldset>
              </div>
              <div class="col-xs-4">
                <fieldset class="form-group">
                  <fieldset class="form-group">
                    <%= f.label :bust_size %>
                    <%= f.text_field :bust_size, class: 'form-control' %>
                  </fieldset>
                </fieldset>
              </div>
              <div class="col-xs-4">
                <fieldset class="form-group">
                  <%= f.label :waist_size %>
                  <%= f.text_field :waist_size, class: 'form-control' %>
                </fieldset>
              </div>
              <div class="col-xs-4">
                <fieldset class="form-group">
                  <%= f.label :hip_size %>
                  <%= f.text_field :hip_size, class: 'form-control' %>
                </fieldset>
              </div>
              <div class="col-xs-12">
                <fieldset class="form-group">
                  <%= f.label :additional_info %>
                  <%= f.text_area :additional_info, class: 'form-control' %>
                </fieldset>
              </div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            Credit Card Information
          </div>
          <div class="card-block" id="credit-card-form">
            <fieldset class="form-group">
              <%= f.label :cardholder_name, "Cardholder's Name*" %>
              <%= f.text_field :cardholder_name, class: 'form-control' %>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :email_address, "E-Mail Address" %>
              <%= f.email_field :email_address, class: 'form-control'%>
            </fieldset>

            <fieldset class="form-group">
              <%= f.label :phone_number, "Phone Number" %>
              <%= f.text_field :phone_number, class: 'form-control' %>
            </fieldset>

            <fieldset class="form-group">
              <%= label_tag :ccNo, "Card Number*" %>
              <%= text_field_tag :ccNo, nil, autocomplete: 'off', class: 'form-control' %>
            </fieldset>

            <fieldset class="form-group">
              <%= label_tag :expirationDate, "Expiration Date (MM/YYYY)*" %>
              <div class="row">
                <div class="col-xs-4">
                  <%= number_field_tag :expMonth, nil, max: 12, placeholder: 'MM', class: 'form-control' %>
                </div>
                <div class="col-xs-4">
                  <%= number_field_tag :expYear, nil, min: Time.now.year, placeholder: 'YYYY', class: 'form-control' %>
                </div>
              </div>
            </fieldset>

            <!-- TODO Add Tooltip explaining verification code location -->
            <fieldset class="form-group">
              <%= label_tag :cvv, "Card Verification Code (3 or 4 digit code on back of the card)*" %>
              <div class="row">
                <div class="col-xs-3">
                  <%= text_field_tag :cvv, nil, autocomplete: 'off', class: 'form-control' %>
                </div>
              </div>
            </fieldset>

            <%= content_tag(:button, 'Authorize Transaction', {role: 'button', class: 'btn btn-primary', id: 'authorize-transaction-button'}) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  var two_checkout_environment = "<%= ENV['two_checkout_environment'] %>";
  var two_checkout_sellerId = "<%= ENV['two_checkout_sellerId'] %>";
  var two_checkout_publishableKey = "<%= ENV['two_checkout_publishableKey'] %>";
</script>

<div id="loading-container">
  <div id="loading-overlay"></div>
  <div id="loading-image">
    <%= image_tag 'wheel.svg', width: 120, height: 120 %>
  </div>
</div>

app/views/orders/show.html.erb
<%
   pagetitle = "My Account - Order No #{@order.order_number}"
   description = 'Rhion Romany Customer Account Order Details Page'
   meta title: pagetitle,
        description: description
%>

<h1 class="text-xs-center" id="pagetitle">My Account</h1>

<%= render 'accounts/account_menu' %>

<div class="page-container container-fluid" id="order-details-container">
  <%= render 'shared/flash_messages' %>
  <div class="card">
    <div class="card-header">
      <h4 class="card-title"><%= @order.collection_item.name %></h4>
      <h5 class="card-subtitle text-muted"><%= @order.collection_item.collection.name %></h5>
    </div>
    <div class="card-block">
      <div class="row">
        <div class="col-xs-12 col-sm-5" id="collection-item-container">
          <%= attachment_image_tag(@order.collection_item, :image, :fit, 650, 600, {alt: @order.collection_item.name, class: 'img-fluid'}) %>
        </div>
        <div class="col-xs-6 col-sm-4" id="order-details">
          <p class="card-text" id="price"><strong>Price: </strong>USD <%= @order.payment %></p>
          <p class="card-text" id="order-status"><strong>Order Status: </strong><%= @order.status.capitalize %></p>
          <%= order_status_date(@order, :p, 'card-text') %>
          <p class="card-text" id="credit-card"><strong>Credit Card: </strong><%= @order.credit_card %></p>
          <p class="card-text" id="address">
            <strong>Order Address:</strong>
            <address>
              <%= @order.address.street_address_1 %><br/>
              <% unless @order.address.street_address_2.nil? or @order.address.street_address_2.blank? %>
                <%= @order.address.street_address_2 %><br/>
              <% end %>
              <%= @order.address.city %><br/>
              <% unless @order.address.state.nil? or @order.address.state.blank? %>
                <%= @order.address.state %> <%= @order.address.zip_code %><br/>
              <% end %>
              <%= @order.address.country %>
            </address>
          </p>
        </div>
        <div class="col-xs-6 col-sm-2" id="order-options">
          <div class="btn-group-vertical">
            <% if @order.submitted? %>
              <%= link_to 'Payment Errors', account_order_payment_errors_path(@order), class: 'btn btn-secondary' %>
              <%= link_to 'Retry Payment', account_order_retry_payment_path(@order), class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>